//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTERNS_HUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Place { get; set; }
        public string Phone { get; set; }
        public string HighestQualification { get; set; }
        public string YearOfCompletion { get; set; }
        public string Experiance { get; set; }
        public string ResumeFile { get; set; }
    
        public virtual UserLoginCredential UserLoginCredential { get; set; }
    }
}
